### ISSUE TITLE
Changing an input value is not typing, will break if value changes onchange, like in masked inputs

### ISSUE THREAD

**Issue by sompylasar** [Gpx/user-event#25]
`fireEvent.change` in `type` in a loop over text slices.

**Comment by Gpx** [comment]
Can you please provide an example of a failing example?

**Comment by weyert** [comment]
I have created a proposal for resolving this problem. I am having a custom input component which `event.preventDefault()` on `onKeydown` to prevent the typing of non-numeric characters. This means the `change` doesn't get triggered for the character hence should be skipped when dispatching the `change`-event later one

I am only experiencing something weird with running unit tests... separately they all run fine but when you run them together it sometimes breaks 🤷‍♂️

**Comment by Gpx** [comment]
I'm closing this then. Thanks, @weyert for working on it and @sompylasar for noticing the problem
