### ISSUE TITLE
Question - Support for drag and drop and advanced actions

### ISSUE THREAD

**Issue by deadnight7** [Gpx/user-event#95]
Hi Giorgio / Team,

Need to know whether do we have any support for advanced user interactions like
- drag-drop, 
- Mouse Hover, 
- Click and hold 
just like we have in Selenium WebDriver's [Actions Class](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/interactions/Actions.java), 

If yes - Can you please point me to correct documentation reference?

**Comment by Gpx** [comment]
Hi, no there's no support for those actions. I don't think we can implement them either except for click and hold. RTL tests run on top of jsdom, as a consequence, all elements have not width or height making it impossible to handle mouse events correctly.

If you need to test these kinds of events correctly I think you should stick with Selenium or Cypress.

**Comment by cpandit201** [comment]
Thank you for updating.

**Comment by Gpx** [comment]
I'm going to close this issue for now but feel free to add comments to it
