### ISSUE TITLE
Disabled checkbox click still fires `onChange`

### ISSUE THREAD

**Issue by twhitbeck** [Gpx/user-event#96]
this PR on `react-testing-library` was an attempt to address this problem:
https://github.com/kentcdodds/dom-testing-library/pull/217

but it was closed in favor of addressing in this library. From what I can tell, it has not been addressed in this library. In my test, I'm still seeing the `onChange` handler being called for an `<input type="checkbox" disabled />` when I call `userEvent.click(checkbox)`.
This is not how browsers behave, fwiw

**Comment by Gpx** [comment]
Hi, I will try to take a look at this one in the following days

**Comment by twhitbeck** [comment]
It looks to me like `click` events do not fire on checkboxes that are disabled when they are clicked.

https://codepen.io/anon/pen/ZZyqoX

Is it as simple as checking `!checkbox.disabled` before running any of the code in this fn:
https://github.com/Gpx/user-event/blob/master/src/index.js#L34

**Comment by twhitbeck** [comment]
and just to confirm, I checked React's handling of clicking a disabled checkbox.

https://codesandbox.io/s/m788qlylkx

`onChange` does _not_ fire when the `disabled` checkbox is clicked

**Comment by Dhalton** [comment]
I'd also like to bring up the fact that this also happens for a radio button input that is disabled. I see that there is a PR to fix this issue for checkboxes, but it doesn't look like it will fix the problem for radio buttons. If you need me to open a separate issue for that, just let me know. Thanks!

**Comment by Gpx** [comment]
@Dhalton you're right the solution should be similar, would you like to work on it?

**Comment by Dhalton** [comment]
@Gpx I'll take a crack at it, sure. 😄

**Comment by Dhalton** [comment]
@Gpx 
Got a PR to handle this for radio buttons as well. Sorry for the wait, I've been busy! 😃 
#107
